package com.company.model;

public enum AuditActionType {
    EMPLOYEE_DASHBOARD_VIEW,
    VACATION_REQUEST_SUBMITTED,
    VACATION_REQUEST_SUBMISSION_BLOCKED,
    VACATION_REQUEST_APPROVED,
    VACATION_REQUEST_DENIED
}
