package com.company.model;

public enum AuditActionType {
    EMPLOYEE_DASHBOARD_VIEW,
    VACATION_REQUEST_SUBMITTED,
    VACATION_REQUEST_SUBMISSION_BLOCKED,
    VACATION_REQUEST_APPROVED,
    VACATION_REQUEST_DENIED,
    HR_PROCESSING_ATTEMPT,
    HR_PROCESSING_SUCCESS,
    HR_PROCESSING_FAILED,
    ADMIN_USER_INVITED,
    ADMIN_USER_ACTIVATED,
    ADMIN_USER_DISABLED,
    ADMIN_USER_UPDATED,
    ADMIN_TEAM_CREATED,
    ADMIN_TEAM_UPDATED,
    ADMIN_TEAM_ARCHIVED,
    ADMIN_TEAM_MEMBERSHIP_ADDED,
    ADMIN_TEAM_MEMBERSHIP_REMOVED,
    INTEGRATION_CONFIGURED,
    INTEGRATION_DISABLED,
    HOLIDAY_IMPORTED,
    HOLIDAY_DEPRECATED
}
